# This file was generated by GoReleaser. DO NOT EDIT.
cask "aimonitor" do
  depends_on macos: ">= :sonoma"
  app "AIMonitor.app"
  postflight do
    system_command "#{staged_path}/aimonitor",
                   args: ["config", "set", "autostart", "true"],
                   must_succeed: false
  end

  version "1.0.0-beta.15"

  on_macos do
    sha256 "e78c03fa5a0113eabbeae88d8a2803964b93df282c90c63394da3925b25b3abe"
    url "https://github.com/japananh/aimonitor/releases/download/v#{version}/aimonitor_#{version}_darwin_universal.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "67575d15a361a8977a26c9f5d8435dab6cdc402423d9d003c2f9bbc5b7086094"
      url "https://github.com/japananh/aimonitor/releases/download/v#{version}/aimonitor_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2d7f3623d1904c7075af6c186bf4efb84096fea4f2a5d8b0322db1c7c05a7bd3"
      url "https://github.com/japananh/aimonitor/releases/download/v#{version}/aimonitor_#{version}_linux_arm64.tar.gz"
    end
  end

  name "aimonitor"
  desc "Local-first CLI + macOS menu bar widget for managing multiple Claude OAuth accounts"
  homepage "https://github.com/japananh/aimonitor"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aimonitor"

  uninstall launchctl: [
      "dev.aimonitor.daemon",
    ],
    quit: [
      "dev.aimonitor.AIMonitor",
    ],
    login_item: [
      "dev.aimonitor.AIMonitor",
    ]

  zap trash: [
      "~/Library/LaunchAgents/dev.aimonitor.daemon.plist",
      "~/Library/Application Support/aimonitor",
      "~/Library/Logs/aimonitor",
      "~/Library/Caches/aimonitor",
      "~/Library/Preferences/dev.aimonitor.AIMonitor.plist",
      "~/.config/aimonitor",
      "~/.aimonitor",
      "~/.aimonitor-lock",
    ]

  caveats <<~EOS
    The aimonitor daemon is registered to start at login during install,
    so the menu bar shows live data right away. Opt out any time with:

      aimonitor config set autostart false

    The menu bar app is unsigned in this beta — macOS Gatekeeper blocks
    the first GUI launch. Clear it once:

      xattr -dr com.apple.quarantine /Applications/AIMonitor.app

    For COMPLETE removal — including saved logins in your Keychain, the
    database, and config — run this BEFORE `brew uninstall`:

      aimonitor uninstall --purge
  EOS
end
