# This file was generated by GoReleaser. DO NOT EDIT.
cask "aimonitor" do
  depends_on macos: ">= :sonoma"
  app "AIMonitor.app"
  postflight do
    system_command "#{staged_path}/aimonitor",
                   args: ["config", "set", "autostart", "true"],
                   must_succeed: false
  end

  version "1.0.0-beta.12"

  on_macos do
    sha256 "9e2d29a2874fcdf5745b1d1355dddd5dec15ae6e1968d60978a0b7af7fc6eba1"
    url "https://github.com/japananh/aimonitor/releases/download/v#{version}/aimonitor_#{version}_darwin_universal.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "084818b9ef5780de4cbb7090f963d6629edf5599e83f84c3285cd1596d494a65"
      url "https://github.com/japananh/aimonitor/releases/download/v#{version}/aimonitor_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a834cd579a7c9b8c5d195307b2d37628456f1fa8115eb0d701d8fb8e34b3a75d"
      url "https://github.com/japananh/aimonitor/releases/download/v#{version}/aimonitor_#{version}_linux_arm64.tar.gz"
    end
  end

  name "aimonitor"
  desc "Local-first CLI + macOS menu bar widget for managing multiple Claude OAuth accounts"
  homepage "https://github.com/japananh/aimonitor"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aimonitor"

  uninstall launchctl: [
      "dev.aimonitor.daemon",
    ],
    quit: [
      "dev.aimonitor.AIMonitor",
    ],
    login_item: [
      "dev.aimonitor.AIMonitor",
    ]

  zap trash: [
      "~/Library/LaunchAgents/dev.aimonitor.daemon.plist",
      "~/Library/Application Support/aimonitor",
      "~/Library/Logs/aimonitor",
      "~/Library/Caches/aimonitor",
      "~/Library/Preferences/dev.aimonitor.AIMonitor.plist",
      "~/.config/aimonitor",
      "~/.aimonitor",
      "~/.aimonitor-lock",
    ]

  caveats <<~EOS
    The aimonitor daemon is registered to start at login during install,
    so the menu bar shows live data right away. Opt out any time with:

      aimonitor config set autostart false

    The menu bar app is unsigned in this beta — macOS Gatekeeper blocks
    the first GUI launch. Clear it once:

      xattr -dr com.apple.quarantine /Applications/AIMonitor.app

    For COMPLETE removal — including saved logins in your Keychain, the
    database, and config — run this BEFORE `brew uninstall`:

      aimonitor uninstall --purge
  EOS
end
