# This file was generated by GoReleaser. DO NOT EDIT.
cask "aimonitor" do
  depends_on macos: :sonoma
  app "AIMonitor.app"
  postflight_steps do
    # Strip the Gatekeeper quarantine flag off the freshly-staged,
    # unsigned .app so the GUI opens without the "damaged" /
    # "unidentified developer" block. Homebrew re-stages a fresh,
    # re-quarantined copy on every `brew upgrade`, so this must re-run
    # each time — and it does (the steps run on install AND upgrade).
    run "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "{{appdir}}/AIMonitor.app"],
        writable_paths: ["AIMonitor.app"],
        writable_base: :appdir,
        must_succeed: false
    # Register the daemon at login so the menu bar shows live data at once.
    run "aimonitor",
        base: :staged_path,
        args: ["config", "set", "autostart", "true"],
        must_succeed: false
  end

  version "1.1.59"

  on_macos do
    sha256 "e488a8518483bf000762a8458852c5909e7b1c0735463d7e9ed8cd054222f084"
    url "https://github.com/japananh/aimonitor/releases/download/v#{version}/aimonitor_#{version}_darwin_universal.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "9351bfc6f64dab77831188d99b57e1d9003a87dae49842fc72cbc293bd28fa38"
      url "https://github.com/japananh/aimonitor/releases/download/v#{version}/aimonitor_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "73a72a4bf6d40f5a59c5c58ac5c2fedf46b13e0b7bdeb90d4afa7c104ecc380c"
      url "https://github.com/japananh/aimonitor/releases/download/v#{version}/aimonitor_#{version}_linux_amd64.tar.gz"
    end
  end

  name "aimonitor"
  desc "Local-first CLI + macOS menu bar widget for managing multiple Claude OAuth accounts"
  homepage "https://github.com/japananh/aimonitor"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aimonitor"

  uninstall launchctl: [
      "dev.aimonitor.daemon",
    ],
    quit: [
      "dev.aimonitor.AIMonitor",
    ],
    login_item: [
      "dev.aimonitor.AIMonitor",
    ]

  zap trash: [
      "~/Library/LaunchAgents/dev.aimonitor.daemon.plist",
      "~/Library/Application Support/aimonitor",
      "~/Library/Logs/aimonitor",
      "~/Library/Caches/aimonitor",
      "~/Library/Preferences/dev.aimonitor.AIMonitor.plist",
      "~/.config/aimonitor",
      "~/.aimonitor",
      "~/.aimonitor-lock",
    ]

  caveats <<~EOS
    The aimonitor daemon is registered to start at login during install,
    so the menu bar shows live data right away. Opt out any time with:

      aimonitor config set autostart false

    The menu bar app is unsigned. Install auto-clears the Gatekeeper
    quarantine flag; if macOS still blocks the launch ("damaged" or
    "unidentified developer"), clear it manually:

      xattr -dr com.apple.quarantine /Applications/AIMonitor.app

    For COMPLETE removal — including saved logins in your Keychain, the
    database, and config — run this BEFORE `brew uninstall`:

      aimonitor uninstall --purge
  EOS
end
